### ISSUE TITLE
Cannot resolve foobar.test: Unknown host

### ISSUE THREAD

**Issue by Sylk** [zhwei/valet-phpbrew-ext#3]
Valet appears to be running, and the PhpBrew version of PHP has fpm running.

I ran a `ping foobar.test` and got in response.
`ping: cannot resolve foobar.test: Unknown host`

Am I doing something incorrectly? I've followed the setup for the repo.

**Comment by zhwei** [comment]
*.test is resloved by dnsmasq, can you access other sites in valet ?

**Comment by Sylk** [comment]
As far as I can tell, no. Suggestions?

**Comment by zhwei** [comment]
try reinstall valet https://laravel.com/docs/8.x/valet#installation

**Comment by Sylk** [comment]
Reinstalling valet worked. Thanks for the suggestion @zhwei. I'm closing this now.
